name: 28569 Deploy

on:
  workflow_run:
    workflows: ["28569 Test"]
    types:
      - completed
      
jobs:
  deploy:
    runs-on: Linux
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          # Podatki so v settings -> secrets ->

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/opencv-projekt:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/opencv-projekt:latest
